export const IMG = {
  SPLASH_SCREEN_LOGO: require('../assets/logo.png'),
  SPLASH_SCREEN_BACKGROUND_IMG: require('../assets/background.png'),
  IMAGE_LEFT_ARROW: require('../assets/left-arrow.png'),
  IMAGE_MOBILE_ICON: require('../assets/mobile-icon.png'),
  IMAGE_DRAWER_ITEM_MENU: require('../assets/left-menu-hamburger.png'),
  IMAGE_PROFILE: require('../assets/profile-icon.png'),
  NOCART: require('../assets/noResult/cart-is-empty.png'),
  IMAGE_LOG_OUT: require('../assets/drawer/log-out.png'),
  IMAGE_MENU: require('../assets/drawer/menu.png'),
  IMAGE_NAME: require('../assets/drawer/name.png'),
  IMAGE_PH: require('../assets/drawer/ph.png'),
  IMAGE_FLOWER: require('../assets/flower/flower.png'),
  IMAGE_USER: require('../images/user.png'),
  IMAGE_LOVE: require('../assets/love.png'),

  IMAGE_CART_SMALL: require('../assets/cart/cart.png'),
  IMAGE_CART_BIG: require('../assets/cart/cart-big.png'),
  IMAGE_TRASH: require('../assets/cart/trash.png'),
  LOGO: require('../assets/logo.png'),
  NORESULT: require('../assets/noResult/no-result.png'),
};
